version: "3.8"
services:
  db:
    build: .
    container_name: auth-board-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: auth-board
      LANG: ko_KR.UTF-8
      LC_ALL: ko_KR.UTF-8
      # 아래는 초기 데이터베이스 생성 시 로케일 지정
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=ko_KR.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - auth-board-net

  redis:
    image: redis:7.4.1
    container_name: auth-board-redis
    ports:
      - "6379:6379"
    networks:
      - auth-board-net

networks:
  auth-board-net:
    driver: bridge

volumes:
  db-data:
